
package UI;


import java.sql.Connection;               
import java.sql.DriverManager;          
import java.sql.PreparedStatement;       
import java.sql.ResultSet;              
import java.sql.SQLException;        
import javax.swing.JOptionPane;


public class LoginLandlord extends javax.swing.JFrame {

    /**
     * Creates new form LoginLandlord
     */
    public LoginLandlord() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LLloginbtn = new javax.swing.JButton();
        UnameLandlord = new javax.swing.JTextField();
        PwordLandlord = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(700, 500));
        getContentPane().setLayout(null);

        LLloginbtn.setBackground(new java.awt.Color(153, 153, 255));
        LLloginbtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LLloginbtn.setText("Log in");
        LLloginbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LLloginbtnActionPerformed(evt);
            }
        });
        getContentPane().add(LLloginbtn);
        LLloginbtn.setBounds(310, 280, 75, 23);

        UnameLandlord.setBackground(new java.awt.Color(204, 204, 255));
        getContentPane().add(UnameLandlord);
        UnameLandlord.setBounds(230, 180, 250, 22);

        PwordLandlord.setBackground(new java.awt.Color(204, 204, 255));
        getContentPane().add(PwordLandlord);
        PwordLandlord.setBounds(230, 220, 250, 22);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Password");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(110, 220, 90, 25);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Username");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(110, 180, 90, 25);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Elryne\\Documents\\Background.jpg")); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-30, 0, 700, 500);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LLloginbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LLloginbtnActionPerformed
                                          
   String Username = UnameLandlord.getText();
    String Password = PwordLandlord.getText();

    String sql = "SELECT * FROM landlordlogin WHERE Username = ? AND Password = ?";
    try {
        Connection connect = DriverManager.getConnection("jdbc:mysql://localhost:3306/arfbs", "root", "");
        PreparedStatement pstmt = connect.prepareStatement(sql);
        pstmt.setString(1, Username);
        pstmt.setString(2, Password);
        ResultSet rs = pstmt.executeQuery();

        if (rs.next()) {
            LandlordDashboard dashboard = new LandlordDashboard();
            dashboard.show();
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(rootPane, "Invalid Username or Password!", "Login Error", JOptionPane.ERROR_MESSAGE);
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(rootPane, "An error occurred: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_LLloginbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginLandlord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginLandlord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginLandlord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginLandlord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginLandlord().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LLloginbtn;
    private javax.swing.JPasswordField PwordLandlord;
    private javax.swing.JTextField UnameLandlord;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
