/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;


import ApartmentRentals.tenantdatabase;
import DatabaseConnection.Database;
import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Elryne
 */
public class LoginSignup extends javax.swing.JFrame {
    private Connection connect;

    /**
     * Creates new form LandlordLogin
     */
    public LoginSignup() {
        initComponents();
        Database dbcon = new Database();
           connect = dbcon.getConnection();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        Backbtn = new javax.swing.JButton();
        tenantpasswordfield = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        tenantusernamefield = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        SignUpbtn = new javax.swing.JButton();
        tenantloginbtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(700, 500));
        getContentPane().setLayout(null);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Or");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(360, 330, 37, 16);

        Backbtn.setBackground(new java.awt.Color(153, 153, 153));
        Backbtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Backbtn.setText("Back");
        Backbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackbtnActionPerformed(evt);
            }
        });
        getContentPane().add(Backbtn);
        Backbtn.setBounds(480, 400, 72, 23);
        getContentPane().add(tenantpasswordfield);
        tenantpasswordfield.setBounds(230, 230, 260, 30);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Password");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(140, 220, 80, 20);
        getContentPane().add(tenantusernamefield);
        tenantusernamefield.setBounds(230, 180, 260, 30);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Username");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(140, 180, 80, 20);

        SignUpbtn.setBackground(new java.awt.Color(204, 204, 255));
        SignUpbtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        SignUpbtn.setText("Sign Up");
        SignUpbtn.setToolTipText("");
        SignUpbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignUpbtnActionPerformed(evt);
            }
        });
        getContentPane().add(SignUpbtn);
        SignUpbtn.setBounds(290, 360, 160, 30);

        tenantloginbtn.setBackground(new java.awt.Color(204, 204, 255));
        tenantloginbtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        tenantloginbtn.setText(" Log In");
        tenantloginbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tenantloginbtnActionPerformed(evt);
            }
        });
        getContentPane().add(tenantloginbtn);
        tenantloginbtn.setBounds(290, 290, 160, 30);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Apartment Rental and Facilities Billing System");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(200, 110, 300, 20);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("ARFBS");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(80, 90, 130, 48);

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Elryne\\Documents\\Background.jpg")); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 0, 700, 500);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tenantloginbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tenantloginbtnActionPerformed
          String username = tenantusernamefield.getText().trim();
    String password = new String(tenantpasswordfield.getPassword()).trim();

    // Validate fields are not empty
    if (username.isEmpty() || password.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please fill in both fields.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Validate login credentials using tenantdatabase
    tenantdatabase tenantDB = new tenantdatabase();
    boolean isValid = tenantDB.validateTenantLogin(username, password);

    if (isValid) {
        // Login successful
        JOptionPane.showMessageDialog(this, "Login Successful!", "Welcome", JOptionPane.INFORMATION_MESSAGE);

        // Open tenant dashboard or next screen
        TenantDashboard tenantDashboard = new TenantDashboard();
        tenantDashboard.setVisible(true);

        // Close login window
        this.dispose();
    } else {
        // Login failed
        JOptionPane.showMessageDialog(this, "Invalid Username or Password!", "Login Error", JOptionPane.ERROR_MESSAGE);
    }
  
          
       
    }//GEN-LAST:event_tenantloginbtnActionPerformed

    private void SignUpbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignUpbtnActionPerformed
        {
            SignUp SignUpFrame = new SignUp();
    
    // Set the new frame visible
   SignUpFrame.setVisible(true);
    
    // Optionally, hide the current BillingInterface JFrame
    this.dispose(); // This will close the current frame (BillingInterface)
}       
      
                                         
    }//GEN-LAST:event_SignUpbtnActionPerformed

    private void BackbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackbtnActionPerformed
        {
            GetStarted GetStartedFrame = new GetStarted ();
            GetStartedFrame.setVisible(true);
    
    // Optionally, hide the current BillingInterface JFrame
    this.dispose(); // This will close the current frame (BillingInterface)
}
                                        
    }//GEN-LAST:event_BackbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginSignup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginSignup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginSignup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginSignup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginSignup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Backbtn;
    private javax.swing.JButton SignUpbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JButton tenantloginbtn;
    private javax.swing.JPasswordField tenantpasswordfield;
    private javax.swing.JTextField tenantusernamefield;
    // End of variables declaration//GEN-END:variables
}
