/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import ApartmentRentals.tenantdatabase;
import javax.swing.JOptionPane;

/**
 *
 * @author Elryne
 */
public class SignUp extends javax.swing.JFrame {

    /**
     * Creates new form TenantSignUp
     */
    public SignUp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PasswordfieldPword = new javax.swing.JPasswordField();
        txtfieldUname = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        backbtn = new javax.swing.JButton();
        SignUp2btn = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtfieldLname = new javax.swing.JTextField();
        txtfieldFname = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(700, 500));
        getContentPane().setLayout(null);
        getContentPane().add(PasswordfieldPword);
        PasswordfieldPword.setBounds(220, 260, 260, 22);
        getContentPane().add(txtfieldUname);
        txtfieldUname.setBounds(220, 220, 260, 22);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Contact No.");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(130, 180, 90, 20);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Full Name");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(130, 140, 80, 20);

        backbtn.setBackground(new java.awt.Color(204, 204, 204));
        backbtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        backbtn.setText("Back");
        backbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbtnActionPerformed(evt);
            }
        });
        getContentPane().add(backbtn);
        backbtn.setBounds(490, 400, 75, 23);

        SignUp2btn.setBackground(new java.awt.Color(204, 204, 255));
        SignUp2btn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        SignUp2btn.setText("Sign Up");
        SignUp2btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignUp2btnActionPerformed(evt);
            }
        });
        getContentPane().add(SignUp2btn);
        SignUp2btn.setBounds(300, 360, 90, 27);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Password");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(130, 260, 70, 20);
        getContentPane().add(txtfieldLname);
        txtfieldLname.setBounds(220, 180, 260, 22);
        getContentPane().add(txtfieldFname);
        txtfieldFname.setBounds(220, 140, 260, 22);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Username");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(130, 220, 70, 20);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Apartment Rental and Facilities Billing System");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(210, 100, 290, 20);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ARFBS");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(90, 80, 120, 48);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Elryne\\Documents\\Background.jpg")); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 700, 500);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SignUp2btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignUp2btnActionPerformed
    String FullName = txtfieldFname.getText();
    String ContactNumber = txtfieldLname.getText();
    String Username = txtfieldUname.getText();
    String Password = String.valueOf(PasswordfieldPword.getPassword()).trim();

    // Check if any field is empty
    if (FullName.isEmpty() || ContactNumber.isEmpty() || Username.isEmpty() || Password.isEmpty()) {
        // Show message if any field is empty
        JOptionPane.showMessageDialog(this, "Please fill all the fields to proceed.", "Error", JOptionPane.ERROR_MESSAGE);
        return; // Exit the method to prevent further processing
    }

    // Create an instance of tenantdatabase to interact with the database
    tenantdatabase db = new tenantdatabase();
    
    // Call the method to save the data to the database
    String tenantId = db.saveOrderToDatabase(FullName, ContactNumber, Username, Password);

    // Check if the tenant ID is returned, indicating successful insertion
    if (tenantId != null) {
        // Show success message
        JOptionPane.showMessageDialog(this, "Sign-Up Successful!", "Success", JOptionPane.INFORMATION_MESSAGE);
        
        // Open the TenantDashboard
        TenantDashboard TenantDashboardFrame = new TenantDashboard();
        TenantDashboardFrame.setVisible(true);
        
        // Optionally, close the current sign-up frame
        this.dispose(); // Close the current frame
    } else {
        // Show error if saving to database fails
        JOptionPane.showMessageDialog(this, "Error during sign-up. Please try again.", "Error", JOptionPane.ERROR_MESSAGE);
    
                                          
    }//GEN-LAST:event_SignUp2btnActionPerformed
    }
    private void backbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbtnActionPerformed
      {
            LoginSignup HomePageFrame = new LoginSignup();
            HomePageFrame.setVisible(true);
    
    // Optionally, hide the current BillingInterface JFrame
    this.dispose(); // This will close the current frame (BillingInterface)
}

         
    }//GEN-LAST:event_backbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField PasswordfieldPword;
    private javax.swing.JButton SignUp2btn;
    private javax.swing.JButton backbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField txtfieldFname;
    private javax.swing.JTextField txtfieldLname;
    private javax.swing.JTextField txtfieldUname;
    // End of variables declaration//GEN-END:variables
}
